# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The 5 Minute Code
email: dincio.montesi@gmail.com
description: >-
  Well this seems easy...
logo: "/assets/global/logo.png"
baseurl: "/5mincode" # the subpath of your site, e.g. /blog
url: ""              # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
mathjax: true
google_analytics: UA-125145949-1
disqus:
  shortname: 5mincode

# Build settings
markdown: kramdown
#! DEFAULT THEME: theme: minima
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
